### ISSUE TITLE
Add an example of custom icon with Markers

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/mapbox-gl-rs#30]
https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

**Comment by shimatar0** [comment]
@yukinarit 
Hi! In addressing this issue, found some concerns.
Perhaps this requires creating an HttpElement to customize the MakerOption structure, 
but the HttpElement is likely to skip serialization.
https://github.com/yukinarit/mapbox-gl-rs/blob/main/src/marker.rs#L15-L16

I think that HttpElement may be a bit difficult to deal with as it does not seem to have a `serialize/deserialize trait`🤔
I can't really think of a better idea😂

**Comment by yukinarit** [comment]
Hi @shimatar0! 
Oh, It seems my prior implementation for `MarkerOptions` is pretty much incomplete! This issue shouldn't have "good first issue" label 😂 

Can you please try if this implementation works?

 ```rust
 impl MarkerOptions {
    pub fn build(mut self) -> JsValue {
        let obj: js_sys::Object = serde_wasm_bindgen::to_value(&self).unwrap().into();
        if let Some(element) = self.element.take() {
            js_sys::Object::define_property(&obj, &JsValue::from_str("element"), &*element).into()
        } else {
            obj.into()
        }
     }
 }
```

**Comment by shimatar0** [comment]
@yukinarit 
Thanks! 
I feel that this would allow the structure members themselves to be serialized when passing through the build method.

However, I think the following structure definitions may be the bottleneck.(`HtmlElement`)
e.g.
MarkerOptions
```
    ...
    // todo keep serialization from skipping.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub element: Option<web_sys::HtmlElement>,
    ...
```

Is this error likely?
```
the trait bound `HtmlElement: Serialize` is not satisfied
the following other types implement trait `Serialize`:
```

**Comment by yukinarit** [comment]
Yes, `element` needs to have `#[serde(skip)]`, because it's not serializable. [My implementation](https://github.com/yukinarit/mapbox-gl-rs/issues/30#issuecomment-1518939528) serializes `MarkerOptions` without `element` into `JsValue` first. Then it appends `element` property of `HtmlElement` into the JsValue. Hope this will work.

**Comment by shimatar0** [comment]
@yukinarit 
Sorry. It took me a while to check😂
I understand, but there still seemed to be a problem, so I put out a PR for WIP and commented!

**Comment by yukinarit** [comment]
Done in https://github.com/yukinarit/mapbox-gl-rs/pull/42
