### ISSUE TITLE
Add example of draggable marker

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/mapbox-gl-rs#38]
https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/

Depends on https://github.com/yukinarit/mapbox-gl-rs/issues/44

**Comment by shimatar0** [comment]
Hi, @yukinarit !
I'm thinking of trying this issue, can I ask you a questions?
- should `Marker` be expanded so that it can have `Event`? (e.g. `MapFactory.set_listener`)

**Comment by yukinarit** [comment]
Oh, this example requires marker event support. I made a separate issue https://github.com/yukinarit/mapbox-gl-rs/issues/44, please do that first, thank you! 🙏

**Comment by shimatar0** [comment]
@yukinarit 
Okay! I'll do #44  first👍
