### ISSUE TITLE
Support Marker events

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/mapbox-gl-rs#44]
https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-events

**Comment by shimatar0** [comment]
@yukinarit 
Hi! 
I've tried to implement it once itself, but I'm unclear again, so please let me issue a PR on WIP 🙇
Would it be easier to understand the errors if I also include examples of use?( #38 )

**Comment by yukinarit** [comment]
@shimatar0 Ah, yes you can include an example in the PR 🙏

**Comment by shimatar0** [comment]
@yukinarit 
Okey, included and pushed!
