### ISSUE TITLE
Add an example of Leptos

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/mapbox-gl-rs#9]
https://github.com/gbj/leptos

**Comment by shimatar0** [comment]
@yukinarit 
Hi, I would like to try this.
I've put out a PR and hope you'll check it out when you have time.

**Comment by yukinarit** [comment]
@shimatar0 Of course 👍 Feel free to ask any questions!

**Comment by shimatar0** [comment]
@yukinarit 
I have issued a PR that corresponds to this one.
This project is very interesting and I would like to know if there are other issues that need to be addressed! (I'm still a newbie to Rust.😓)

**Comment by yukinarit** [comment]
@shimatar0 OKay, I will create more issues 👌
